category:
    resource: '@PimApiBundle/Resources/config/routing/category.yml'
    prefix: /rest/v1/

family:
    resource: '@PimApiBundle/Resources/config/routing/family.yml'
    prefix: /rest/v1

attribute:
    resource: '@PimApiBundle/Resources/config/routing/attribute.yml'
    prefix: /rest/v1

product:
    resource: '@PimApiBundle/Resources/config/routing/product.yml'
    prefix: /rest/v1
